### PR TITLE
fixed a bug

### PR DESCRIPTION
**Pull request by rohith-vishnu**
## Description
Just a small change in the code, in the code the the split function is used to split with a character ' , '
but the r2 object has text which has to be separated with a character ' ; ' (semicolon).
with out which the program when executed gives an array out of bound exception. So this small change to the code will remove that error.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by meholden** [comment]
Thanks for finding this bug.  Originally data was split with commas but this was recently changed to semicolons and I did not update that file.

**Comment by TalAter** [comment]
Thank you @rohith-vishnu 
How was the experience of running n3m0? What was your motivation for trying? Would love to hear more from you. You can reach me at tal@dav.network

**Comment by rohith-vishnu** [comment]
Hey
I was in a open-source hackathon and was finding projects which were in
early stages. So found this one, I couldn't completely run the project yet
but will try it out....very nice idea if it comes to implementation in real
then it would be so cool.
Thank you

**Comment by TalAter** [comment]
Awesome! Thank you @rohith-vishnu 
Check out some of the things we are building here: https://dav.network/prototypes.html

**Pull request merged**
